from .basemodel import BaseModel
from .basiswert import Basiswert
from .eigenschaft import Eigenschaft
from .fertigkeit import Fertigkeit
from .held import Held
from .kultur import Kultur
from .merkmal import Merkmal
from .nachteil import Nachteil
from .profession import Profession
from .spezies import Spezies
from .vorteil import Vorteil
